task :default => ['c:wn']

file 'SAP.class' => ['SAP.java'] do
  sh 'javac SAP.java'
end

file 'WordNet.class' => ['WordNet.java'] do
  sh 'javac WordNet.java'
end

file 'WordNetTest.class' => ['WordNetTest.java'] do
  sh 'javac WordNetTest.java'
end

namespace :c do
  desc "Compile SAP.java"
  task :sap => ['SAP.java'] do
    sh 'javac SAP.java'
  end

  desc "Compile WordNet.java"
  task :wn => ['WordNet.java', 'SAP.class'] do
    sh 'javac WordNet.java'
  end

  desc "Compile Outcast.java"
  task :out => ['Outcast.java', 'WordNet.class', 'SAP.class'] do
    sh 'javac Outcast.java'
  end
end

namespace :r do
  desc "Run SAP's public main"
  task :sap => ['SAP.class'] do
    sh 'java SAP'
  end

  desc "Run WordNet's public main"
  task :wn => ['WordNet.class, SAP.class'] do
    sh 'java WordNet'
  end

  desc "Run Outcast test"
  task :out => ['Outcast.class', 'WordNet.class', 'SAP.class'] do
    sh 'java Outcast data/synsets.txt data/hypernyms.txt data/outcast5.txt data/outcast8.txt data/outcast11.txt'
  end
end

namespace :t do
  desc "Test WordNet class"
  task :wn => ['WordNet.class', 'WordNetTest.class'] do
    sh 'java -cp .:../lib/junit-4.11.jar:../lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore WordNetTest'
  end
end

task :prep do
  sh 'zip wordnet.zip SAP.java WordNet.java Outcast.java'
end
